import { LISTING_CARD_IMAGE_ASPECT_RATIO, lobbyDesign } from '@lobby/shared';
import { Platform, StyleSheet } from 'react-native';
import { L } from './lovableTokens';

const C = lobbyDesign.colors;
const BRAND_BORDER = 'rgba(0, 157, 224, 0.25)';

export const appStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 100,
  },
  headerGlass: {
    borderBottomWidth: 1,
    borderBottomColor: C.border,
    backgroundColor: 'rgba(255,255,255,0.92)',
    paddingBottom: 4,
  },
  headerGlassRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 56,
    marginHorizontal: 12,
    paddingHorizontal: 4,
  },
  brandLogoMark: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: C.brand,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandLogoMarkText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  brandLogoWord: {
    color: C.foreground,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  heroSection: {
    alignItems: 'stretch',
    paddingTop: 0,
    paddingBottom: 14,
  },
  heroSiteBanner: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderRadius: 16,
    backgroundColor: C.brand,
    shadowColor: 'rgba(0, 157, 224, 0.35)',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 4,
  },
  heroSiteBannerMark: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroSiteBannerMarkText: {
    fontSize: 18,
    fontWeight: '900',
    color: '#ffffff',
  },
  heroSiteBannerTextWrap: {
    flex: 1,
    alignItems: 'flex-end',
  },
  heroSiteBannerTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.3,
  },
  heroSiteBannerSub: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.92)',
  },
  heroBadge: {
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: C.brandSoft,
  },
  heroBadgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: C.brand,
  },
  heroTitle: {
    textAlign: 'center',
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '900',
    color: C.foreground,
    letterSpacing: -0.5,
  },
  heroTitleBrand: {
    color: C.brand,
  },
  heroSub: {
    marginTop: 10,
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 20,
    color: C.muted,
    maxWidth: 320,
  },
  heroSearchBubble: {
    position: 'relative',
    width: '100%',
    marginTop: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: 'rgba(15, 23, 42, 0.08)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  heroSearchLabel: {
    textAlign: 'right',
    fontSize: 12,
    fontWeight: '500',
    color: C.muted,
  },
  heroSearchValue: {
    marginTop: 4,
    textAlign: 'right',
    fontSize: 15,
    fontWeight: '700',
    color: C.foreground,
    paddingLeft: 28,
  },
  heroSearchHint: {
    marginTop: 4,
    textAlign: 'right',
    fontSize: 12,
    color: C.muted,
  },
  heroSearchIcon: {
    position: 'absolute',
    left: 16,
    top: '50%',
    marginTop: -11,
    fontSize: 22,
    fontWeight: '700',
    color: C.brand,
  },
  heroChipsRow: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 6,
    marginTop: 14,
  },
  heroChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surfaceSoft,
  },
  heroChipText: {
    fontSize: 12,
    color: 'rgba(32, 33, 37, 0.75)',
    fontWeight: '500',
  },
  header: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    marginHorizontal: 14,
    marginBottom: 4,
    paddingHorizontal: 2,
    paddingVertical: 4,
    borderRadius: 0,
    backgroundColor: 'transparent',
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  brandLogoText: {
    color: C.foreground,
    fontSize: 20,
    fontWeight: '900',
    letterSpacing: -0.5,
  },
  headerAuthCluster: {
    position: 'absolute',
    right: 2,
    top: 0,
    bottom: 0,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 14,
    maxWidth: 200,
  },
  headerMuted: {
    fontSize: 13,
    fontWeight: '700',
    color: C.muted,
  },
  headerAuthAction: {
    position: 'absolute',
    right: 2,
    top: 0,
    bottom: 0,
    minWidth: 36,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  headerPublishAction: {
    position: 'absolute',
    left: 2,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
  },
  headerPublishGlow: {
    paddingHorizontal: 10,
    borderRadius: 999,
  },
  headerTextButton: {
    color: C.foreground,
    fontSize: 14,
    fontWeight: '700',
  },
  headerPublishText: {
    color: C.brand,
    fontWeight: '700',
  },
  backArrowIcon: {
    position: 'relative',
    width: 24,
    height: 24,
  },
  backArrowShaft: {
    position: 'absolute',
    top: 11,
    right: 3,
    width: 18,
    height: 2.4,
    borderRadius: 999,
    backgroundColor: C.foreground,
  },
  backArrowHead: {
    position: 'absolute',
    top: 7,
    right: 3,
    width: 10,
    height: 10,
    borderTopWidth: 2.4,
    borderRightWidth: 2.4,
    borderColor: C.foreground,
    borderRadius: 1,
    transform: [{ rotate: '45deg' }],
  },
  filterIcon: {
    width: 17,
    gap: 3,
  },
  filterLine: {
    position: 'relative',
    height: 2,
    borderRadius: 999,
    backgroundColor: C.foreground,
  },
  filterKnob: {
    position: 'absolute',
    top: -2,
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: C.foreground,
  },
  filterKnobRight: {
    right: 2,
  },
  filterKnobLeft: {
    left: 2,
  },
  filterKnobCenter: {
    left: 6,
  },
  bannerCarousel: {
    paddingTop: 4,
    paddingBottom: 10,
  },
  bannerCard: {
    overflow: 'hidden',
    borderRadius: 26,
    shadowColor: C.foreground,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 3,
  },
  bannerBackgroundImage: {
    borderRadius: 26,
  },
  bannerIndicators: {
    flexDirection: 'row',
    alignSelf: 'center',
    gap: 6,
    marginTop: -2,
    marginBottom: 8,
  },
  bannerIndicator: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: C.border,
  },
  bannerIndicatorActive: {
    width: 22,
    backgroundColor: C.brand,
  },
  filterPanel: {
    marginTop: 4,
    marginBottom: 14,
    padding: 10,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.86)',
    shadowColor: C.foreground,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.06,
    shadowRadius: 22,
    elevation: 2,
  },
  filterSearchRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: C.surfaceSoft,
  },
  filterSearchTextWrap: {
    flex: 1,
    minWidth: 0,
    marginLeft: 10,
  },
  filterSearchLabel: {
    textAlign: 'right',
    color: C.muted,
    fontSize: 12,
    fontWeight: '500',
  },
  filterSearchValue: {
    marginTop: 2,
    textAlign: 'right',
    color: C.foreground,
    fontSize: 15,
    fontWeight: '700',
  },
  filterSearchHint: {
    marginTop: 4,
    textAlign: 'right',
    color: C.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  filterSearchIcon: {
    color: C.primary,
    fontSize: 22,
    fontWeight: '700',
  },
  filterMoreButton: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 18,
    backgroundColor: '#fff',
  },
  filterMoreText: {
    color: C.action,
    fontWeight: '700',
  },
  filterClearButton: {
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: C.actionSoft,
    alignItems: 'center',
  },
  filterClearButtonText: {
    color: C.action,
    fontWeight: '700',
    fontSize: 15,
  },
  sectionHeader: {
    gap: 10,
    marginBottom: 12,
  },
  feedToolbarBlock: {
    gap: 10,
    marginBottom: 12,
  },
  sectionTitle: {
    textAlign: 'right',
    color: C.foreground,
    fontSize: 21,
    fontWeight: '700',
  },
  feedSortRow: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-start',
  },
  feedSortPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: C.surfaceSoft,
  },
  feedSortPillOn: {
    backgroundColor: C.actionSoft,
    borderWidth: 1,
    borderColor: BRAND_BORDER,
  },
  feedSortPillText: {
    fontSize: 13,
    fontWeight: '700',
    color: C.foreground,
  },
  feedSortPillTextOn: {
    color: C.foreground,
  },
  feedLoadingText: {
    textAlign: 'center',
    color: C.muted,
    fontSize: 15,
    fontWeight: '700',
    paddingVertical: 20,
    paddingHorizontal: 12,
  },
  cards: {
    gap: 14,
  },
  card: {
    overflow: 'hidden',
    borderRadius: 12,
    backgroundColor: C.card,
    borderWidth: 1,
    borderColor: 'rgba(15, 23, 42, 0.1)',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  imageWrap: {
    position: 'relative',
    width: '100%',
    aspectRatio: LISTING_CARD_IMAGE_ASPECT_RATIO,
    backgroundColor: '#f1f5f9',
  },
  cardSaveBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 2,
  },
  cardImage: {
    width: '100%',
    height: '100%',
  },
  cardBody: {
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  cardPrice: {
    textAlign: 'right',
    color: C.foreground,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  cardAddress: {
    marginTop: 4,
    textAlign: 'right',
    color: C.foreground,
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 18,
  },
  cardMeta: {
    marginTop: 2,
    textAlign: 'right',
    color: '#64748b',
    fontSize: 12,
    lineHeight: 16,
  },
  cardTitle: {
    marginTop: 6,
    textAlign: 'right',
    color: C.foreground,
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  cardLocation: {
    marginTop: 4,
    textAlign: 'right',
    color: '#64748b',
    fontSize: 12,
    lineHeight: 18,
  },
  cardStatsRow: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 10,
  },
  cardStat: {
    color: 'rgba(32, 33, 37, 0.7)',
    fontSize: 12,
    fontWeight: '500',
  },
  cardTypeBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 2,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(32, 33, 37, 0.8)',
  },
  cardTypeBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '600',
  },
  featureRow: {
    flexDirection: 'row-reverse',
    gap: 6,
    marginTop: 12,
  },
  featurePill: {
    flexShrink: 0,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    color: 'rgba(32, 33, 37, 0.7)',
    backgroundColor: '#f8f9fa',
    fontSize: 11,
    fontWeight: '500',
  },
  trustStrip: {
    marginTop: 18,
    padding: 15,
    borderRadius: 22,
    backgroundColor: '#fff',
  },
  trustTitle: {
    textAlign: 'right',
    color: C.foreground,
    fontWeight: '700',
  },
  trustText: {
    marginTop: 4,
    textAlign: 'right',
    color: C.muted,
  },
  listingDetailsRoot: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  listingDetailsScroll: {
    flex: 1,
  },
  detailContent: {
    padding: 14,
    paddingBottom: 100,
  },
  detailCard: {
    marginTop: 16,
    padding: 20,
    borderRadius: 16,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: 'rgba(15, 23, 42, 0.06)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 2,
  },
  detailPriceHero: {
    textAlign: 'right',
    color: '#202125',
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  detailPriceSub: {
    marginTop: 4,
    textAlign: 'right',
    color: '#64748b',
    fontSize: 13,
  },
  detailTypePill: {
    alignSelf: 'flex-end',
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: C.border,
  },
  detailTypePillText: {
    color: 'rgba(32, 33, 37, 0.7)',
    fontSize: 12,
    fontWeight: '600',
  },
  detailTitle: {
    textAlign: 'right',
    color: C.foreground,
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.4,
    lineHeight: 28,
  },
  detailLocation: {
    marginTop: 10,
    textAlign: 'right',
    color: C.muted,
    fontSize: 15,
  },
  statsGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  statBox: {
    minWidth: '47%',
    flex: 1,
    minHeight: 72,
    paddingHorizontal: 12,
    paddingVertical: 14,
    borderRadius: 16,
    backgroundColor: '#f8f9fa',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statLabelRow: {
    marginBottom: 4,
  },
  statValue: {
    textAlign: 'center',
    color: C.brand,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  statLabel: {
    textAlign: 'center',
    color: '#64748b',
    fontSize: 12,
    fontWeight: '600',
  },
  detailSectionTitle: {
    marginTop: 22,
    textAlign: 'right',
    color: C.foreground,
    fontSize: 19,
    fontWeight: '700',
  },
  detailDescription: {
    marginTop: 8,
    textAlign: 'right',
    color: '#202125',
    fontSize: 17,
    lineHeight: 28,
    fontWeight: '400',
  },
  detailDescriptionCard: {
    marginTop: 16,
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#F8F9FA',
  },
  descriptionToggle: {
    alignSelf: 'flex-end',
    marginTop: 8,
    paddingVertical: 2,
  },
  descriptionToggleText: {
    color: C.brand,
    fontSize: 13,
    fontWeight: '700',
  },
  reportModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 14,
    backgroundColor: 'rgba(16,24,32,0.28)',
  },
  reportKeyboardAvoidingView: {
    flex: 1,
  },
  reportSheet: {
    maxHeight: '88%',
    padding: 18,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.97)',
    shadowColor: C.foreground,
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.18,
    shadowRadius: 38,
    elevation: 12,
  },
  reportSheetContent: {
    paddingBottom: 2,
  },
  reportSheetHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    gap: 16,
  },
  reportCloseButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    backgroundColor: '#f3f0e9',
  },
  reportCloseText: {
    color: C.foreground,
    fontSize: 24,
    lineHeight: 28,
  },
  reportTitle: {
    textAlign: 'right',
    color: C.foreground,
    fontSize: 21,
    fontWeight: '800',
  },
  reportSubtitle: {
    marginTop: 6,
    textAlign: 'right',
    color: C.muted,
    fontSize: 14,
  },
  reportReasonList: {
    gap: 8,
    marginTop: 18,
  },
  reportReasonButton: {
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderWidth: 1,
    borderColor: 'rgba(16,24,32,0.07)',
    borderRadius: 18,
    backgroundColor: C.surfaceSoft,
  },
  selectedReportReasonButton: {
    borderColor: 'rgba(8,184,200,0.42)',
    backgroundColor: C.actionSoft,
  },
  reportReasonText: {
    textAlign: 'right',
    color: C.foreground,
    fontWeight: '700',
  },
  selectedReportReasonText: {
    color: C.action,
  },
  reportOtherField: {
    gap: 7,
    marginTop: 12,
  },
  reportOtherLabel: {
    textAlign: 'right',
    color: C.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  reportOtherInput: {
    minHeight: 76,
    paddingHorizontal: 13,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: 'rgba(16,24,32,0.08)',
    borderRadius: 18,
    color: C.foreground,
    backgroundColor: C.surfaceSoft,
    fontSize: 14,
    lineHeight: 20,
  },
  reportOtherCounter: {
    alignSelf: 'flex-start',
    color: C.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  reportSubmitButton: {
    alignItems: 'center',
    marginTop: 14,
    padding: 14,
    borderRadius: 999,
    backgroundColor: C.foreground,
  },
  disabledReportSubmitButton: {
    opacity: 0.35,
  },
  reportSubmitText: {
    color: '#fff',
    fontWeight: '800',
  },
  reportSuccessBanner: {
    marginTop: 10,
    padding: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(8,184,200,0.14)',
    color: '#065a63',
    textAlign: 'right',
    fontWeight: '800',
  },
  reportErrorBanner: {
    marginTop: 10,
    padding: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(220,53,69,0.1)',
    color: '#a21e2e',
    textAlign: 'right',
    fontWeight: '800',
  },
  publisherCard: {
    marginTop: 16,
    padding: 20,
    borderRadius: 16,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: C.border,
    shadowColor: 'rgba(15, 23, 42, 0.06)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 2,
  },
  publisherRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    marginBottom: 4,
  },
  publisherAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.brand,
  },
  publisherAvatarText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '800',
  },
  publisherName: {
    flex: 1,
    textAlign: 'right',
    color: C.foreground,
    fontSize: 17,
    fontWeight: '700',
  },
  publisherSubtitle: {
    textAlign: 'right',
    color: '#64748b',
    fontSize: 12,
    marginTop: 2,
  },
  publisherResponse: {
    marginTop: 4,
    textAlign: 'right',
    color: C.muted,
  },
  phoneButton: {
    marginTop: 16,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(16,24,32,0.1)',
    backgroundColor: '#ffffff',
    shadowColor: 'rgba(16,24,32,0.08)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  phoneButtonText: {
    textAlign: 'center',
    color: '#202125',
    fontSize: 16,
    fontWeight: '700',
  },
  chatButton: {
    marginTop: 12,
    paddingVertical: 16,
    borderRadius: 999,
    backgroundColor: C.brand,
    shadowColor: 'rgba(0, 157, 224, 0.35)',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 3,
  },
  chatButtonText: {
    textAlign: 'center',
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  chatButtonDisabled: {
    opacity: 0.55,
  },
  chatHintText: {
    marginTop: 8,
    textAlign: 'right',
    color: '#a21e2e',
    fontWeight: '700',
    fontSize: 13,
  },
  chatScreenRoot: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  chatScreenInner: {
    flex: 1,
  },
  chatHeaderBar: {
    marginHorizontal: 0,
    marginBottom: 0,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e4e5e7',
    backgroundColor: '#ffffff',
  },
  chatHeaderActionText: {
    fontSize: 15,
    fontWeight: '700',
    color: C.foreground,
  },
  chatScreenTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: C.foreground,
    letterSpacing: -0.4,
  },
  chatSectionLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#74767e',
    letterSpacing: 1,
  },
  chatSearchBar: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e4e5e7',
    backgroundColor: '#ffffff',
  },
  chatSearchInput: {
    borderWidth: 1,
    borderColor: '#e4e5e7',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    backgroundColor: '#fafafa',
    color: C.foreground,
  },
  chatLegalNoticeMobile: {
    paddingHorizontal: 16,
    paddingBottom: 8,
    textAlign: 'right',
    fontSize: 12,
    fontWeight: '500',
    color: '#74767e',
    lineHeight: 17,
  },
  chatListScroll: {
    flex: 1,
  },
  chatListContent: {
    paddingHorizontal: 16,
    paddingBottom: 100,
    flexGrow: 1,
  },
  chatListError: {
    textAlign: 'right',
    fontSize: 13,
    fontWeight: '700',
    color: '#a21e2e',
    marginBottom: 8,
  },
  chatEmptyWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    paddingHorizontal: 24,
    minHeight: 200,
  },
  chatEmptyIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(0, 157, 224, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  chatEmptyTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: C.foreground,
    textAlign: 'center',
    marginBottom: 6,
  },
  chatEmptyHint: {
    fontSize: 13,
    fontWeight: '500',
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 20,
    maxWidth: 280,
  },
  chatMuted: {
    textAlign: 'right',
    color: C.muted,
    fontWeight: '700',
    paddingHorizontal: 16,
    marginTop: 8,
  },
  chatCta: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 14,
    borderRadius: 999,
    backgroundColor: C.foreground,
  },
  chatCtaText: {
    textAlign: 'center',
    color: '#fff',
    fontWeight: '900',
  },
  chatThreadRowShell: {
    flexDirection: 'row-reverse',
    alignItems: 'stretch',
    borderBottomWidth: 1,
    borderBottomColor: '#e4e5e7',
    backgroundColor: '#ffffff',
  },
  chatThreadRowShellUnread: {
    backgroundColor: 'rgba(8, 184, 200, 0.07)',
  },
  chatThreadRow: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 6,
  },
  chatThreadTitleRow: {
    flex: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
    minWidth: 0,
  },
  chatThreadUnreadDot: {
    width: 9,
    height: 9,
    borderRadius: 999,
    backgroundColor: C.primary,
    flexShrink: 0,
  },
  chatThreadRowTop: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  chatThreadTime: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8b949b',
    flexShrink: 0,
  },
  chatThreadPreviewRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  chatThreadPreview: {
    flex: 1,
    textAlign: 'right',
    fontSize: 14,
    fontWeight: '600',
    color: C.muted,
  },
  chatThreadUnreadPill: {
    minWidth: 22,
    height: 22,
    paddingHorizontal: 6,
    borderRadius: 999,
    backgroundColor: C.primary,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  chatThreadUnreadPillText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  chatThreadTitle: {
    textAlign: 'right',
    fontSize: 17,
    fontWeight: '800',
    color: C.foreground,
  },
  chatThreadMeta: {
    marginTop: 4,
    textAlign: 'right',
    fontSize: 13,
    color: C.muted,
  },
  chatThreadSubtitle: {
    paddingHorizontal: 16,
    marginBottom: 4,
    textAlign: 'right',
    fontSize: 15,
    fontWeight: '800',
    color: C.foreground,
  },
  chatThreadBody: {
    flex: 1,
  },
  chatMessagesScroll: {
    flex: 1,
  },
  chatMessagesContent: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 12,
  },
  chatBubbleColumn: {
    maxWidth: '85%',
    gap: 4,
  },
  chatBubbleColumnMine: {
    alignSelf: 'flex-start',
  },
  chatBubbleColumnOther: {
    alignSelf: 'flex-end',
    alignItems: 'flex-end',
  },
  chatBubble: {
    padding: 12,
    borderRadius: 18,
  },
  chatBubbleMine: {
    backgroundColor: 'rgba(8,184,200,0.2)',
  },
  chatBubbleOther: {
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#e4e5e7',
  },
  chatBubbleText: {
    textAlign: 'right',
    fontSize: 15,
    lineHeight: 21,
    color: C.foreground,
  },
  chatBubbleTime: {
    fontSize: 11,
    fontWeight: '600',
    color: C.muted,
    paddingHorizontal: 4,
  },
  chatSendError: {
    paddingHorizontal: 16,
    marginBottom: 6,
    textAlign: 'right',
    fontSize: 13,
    fontWeight: '700',
    color: '#a21e2e',
  },
  chatComposerWrap: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#e4e5e7',
    backgroundColor: '#ffffff',
  },
  chatComposerBar: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-end',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(16,24,32,0.1)',
    backgroundColor: '#fafafa',
  },
  chatComposerIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 999,
    backgroundColor: C.foreground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatComposerIconBtnPressed: {
    opacity: 0.88,
  },
  chatInputBar: {
    flex: 1,
    minHeight: 40,
    maxHeight: 120,
    paddingHorizontal: 4,
    paddingVertical: Platform.OS === 'ios' ? 10 : 8,
    fontSize: 16,
    lineHeight: 22,
    color: C.foreground,
  },
  chatComposerSendBtn: {
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatComposerSendBtnDisabled: {
    opacity: 0.55,
  },
  chatComposerSendBtnPressed: {
    opacity: 0.75,
  },
  mainShell: {
    flex: 1,
  },
  headerMainSimple: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 48,
    marginHorizontal: 10,
    marginBottom: 4,
    paddingHorizontal: 4,
  },
  headerSideSlotEnd: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 2,
  },
  headerSideSlot: {
    minWidth: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  floatingTabBarWrap: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: Platform.OS === 'ios' ? 12 : 10,
    alignItems: 'center',
  },
  floatingTabBar: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: 420,
    paddingVertical: 8,
    paddingHorizontal: 8,
    backgroundColor: '#fff',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(16,24,32,0.07)',
    shadowColor: C.foreground,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 28,
    elevation: 14,
  },
  tabBarMessagesSlot: {
    flex: 1,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabBarBadge: {
    position: 'absolute',
    top: 2,
    right: '18%',
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 999,
    backgroundColor: L.unread,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  tabBarBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '900',
  },
  tabBarItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    paddingVertical: 4,
    borderRadius: 999,
  },
  tabBarItemActive: {
    backgroundColor: C.brandSoft,
  },
  tabBarItemPublish: {
    paddingHorizontal: 4,
    backgroundColor: C.brandSoft,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: BRAND_BORDER,
  },
  tabBarItemActivePublish: {
    backgroundColor: 'rgba(0, 157, 224, 0.18)',
    borderColor: 'rgba(0, 157, 224, 0.35)',
  },
  filterModalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  filterModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(16, 24, 32, 0.35)',
  },
  filterModalSheet: {
    maxHeight: '78%',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: '#ffffff',
    paddingBottom: Platform.OS === 'ios' ? 28 : 16,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: 'rgba(16,24,32,0.08)',
  },
  filterModalHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    marginTop: 10,
    marginBottom: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(16,24,32,0.12)',
  },
  filterModalHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(16,24,32,0.06)',
  },
  filterModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: C.foreground,
  },
  filterModalClose: {
    fontSize: 15,
    fontWeight: '700',
    color: C.primary,
  },
  filterModalBody: {
    padding: 16,
    paddingBottom: 28,
    gap: 4,
  },
  filterModalHint: {
    marginTop: 16,
    textAlign: 'right',
    fontSize: 13,
    lineHeight: 20,
    color: C.muted,
  },
  filterModalActiveHint: {
    marginTop: 10,
    textAlign: 'right',
    fontSize: 13,
    lineHeight: 20,
    color: C.action,
    fontWeight: '600',
  },
  filterModalHintMuted: {
    marginTop: 12,
    textAlign: 'right',
    fontSize: 12,
    lineHeight: 18,
    color: '#9aa3ab',
  },
  phoneButton: {
    marginTop: 10,
    padding: 14,
    borderRadius: 16,
    backgroundColor: C.surfaceSoft,
  },
  phoneButtonText: {
    textAlign: 'center',
    color: C.foreground,
    fontWeight: '700',
  },
  legalFooter: {
    marginTop: 18,
    marginHorizontal: -14,
    marginBottom: -100,
    paddingHorizontal: 18,
    paddingTop: 24,
    paddingBottom: 30,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: C.foreground,
    shadowColor: C.foreground,
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.1,
    shadowRadius: 30,
    elevation: 4,
  },
  footerBrandText: {
    textAlign: 'right',
    color: C.primary,
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: -0.8,
  },
  footerBrandDescription: {
    marginTop: 8,
    textAlign: 'right',
    color: 'rgba(255,255,255,0.7)',
    fontSize: 13,
    lineHeight: 22,
  },
  footerSection: {
    marginTop: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.045)',
  },
  legalFooterTitle: {
    textAlign: 'right',
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
  legalFooterText: {
    marginTop: 6,
    textAlign: 'right',
    color: 'rgba(255,255,255,0.68)',
    fontSize: 13,
    lineHeight: 22,
  },
  footerReportNotice: {
    marginTop: 10,
    marginBottom: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.045)',
  },
  footerLinks: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  footerLinkPill: {
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    color: 'rgba(255,255,255,0.82)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    fontSize: 12,
    fontWeight: '700',
  },
  footerFinePrint: {
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
    textAlign: 'right',
    color: 'rgba(255,255,255,0.58)',
    fontSize: 12,
    lineHeight: 21,
  },
});