import { Platform, StyleSheet } from 'react-native';

export const appStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f7f6f2',
  },
  scrollContent: {
    padding: 14,
    paddingBottom: 100,
  },
  header: {
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    marginHorizontal: 14,
    marginBottom: 4,
    paddingHorizontal: 2,
    paddingVertical: 4,
    borderRadius: 0,
    backgroundColor: 'transparent',
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  brandLogoText: {
    color: '#08b8c8',
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: -0.8,
    textShadowColor: 'rgba(4, 97, 112, 0.28)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 1,
  },
  headerAuthCluster: {
    position: 'absolute',
    right: 2,
    top: 0,
    bottom: 0,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 14,
    maxWidth: 200,
  },
  headerMuted: {
    fontSize: 13,
    fontWeight: '700',
    color: '#5c6670',
  },
  headerAuthAction: {
    position: 'absolute',
    right: 2,
    top: 0,
    bottom: 0,
    minWidth: 36,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  headerPublishAction: {
    position: 'absolute',
    left: 2,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
  },
  headerPublishGlow: {
    paddingHorizontal: 10,
    borderRadius: 999,
  },
  headerTextButton: {
    color: '#101820',
    fontSize: 14,
    fontWeight: '700',
  },
  headerPublishText: {
    color: '#0799a7',
    textShadowColor: 'rgba(8,184,200,0.55)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 9,
  },
  backArrowIcon: {
    position: 'relative',
    width: 24,
    height: 24,
  },
  backArrowShaft: {
    position: 'absolute',
    top: 11,
    right: 3,
    width: 18,
    height: 2.4,
    borderRadius: 999,
    backgroundColor: '#101820',
  },
  backArrowHead: {
    position: 'absolute',
    top: 7,
    right: 3,
    width: 10,
    height: 10,
    borderTopWidth: 2.4,
    borderRightWidth: 2.4,
    borderColor: '#101820',
    borderRadius: 1,
    transform: [{ rotate: '45deg' }],
  },
  filterIcon: {
    width: 17,
    gap: 3,
  },
  filterLine: {
    position: 'relative',
    height: 2,
    borderRadius: 999,
    backgroundColor: '#101820',
  },
  filterKnob: {
    position: 'absolute',
    top: -2,
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#101820',
  },
  filterKnobRight: {
    right: 2,
  },
  filterKnobLeft: {
    left: 2,
  },
  filterKnobCenter: {
    left: 6,
  },
  bannerCarousel: {
    paddingTop: 16,
    paddingBottom: 12,
  },
  bannerCard: {
    height: 190,
    overflow: 'hidden',
    borderRadius: 26,
    shadowColor: '#101820',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 3,
  },
  bannerBackgroundImage: {
    borderRadius: 26,
  },
  bannerIndicators: {
    flexDirection: 'row',
    alignSelf: 'center',
    gap: 6,
    marginTop: -2,
    marginBottom: 8,
  },
  bannerIndicator: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: '#cfc8bb',
  },
  bannerIndicatorActive: {
    width: 22,
    backgroundColor: '#08b8c8',
  },
  filterPanel: {
    marginTop: 4,
    marginBottom: 14,
    padding: 10,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.86)',
    shadowColor: '#101820',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.06,
    shadowRadius: 22,
    elevation: 2,
  },
  filterSearchRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: '#f7f6f2',
  },
  filterSearchTextWrap: {
    flex: 1,
    minWidth: 0,
    marginLeft: 10,
  },
  filterSearchLabel: {
    textAlign: 'right',
    color: '#687076',
    fontSize: 12,
    fontWeight: '500',
  },
  filterSearchValue: {
    marginTop: 2,
    textAlign: 'right',
    color: '#101820',
    fontSize: 15,
    fontWeight: '700',
  },
  filterSearchHint: {
    marginTop: 4,
    textAlign: 'right',
    color: '#687076',
    fontSize: 12,
    lineHeight: 17,
  },
  filterSearchIcon: {
    color: '#08b8c8',
    fontSize: 22,
    fontWeight: '700',
  },
  filterMoreButton: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 18,
    backgroundColor: '#fff',
  },
  filterMoreText: {
    color: '#087b85',
    fontWeight: '700',
  },
  filterClearButton: {
    marginTop: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 18,
    backgroundColor: '#e8fbfd',
    alignItems: 'center',
  },
  filterClearButtonText: {
    color: '#087b85',
    fontWeight: '700',
    fontSize: 15,
  },
  sectionHeader: {
    gap: 10,
    marginBottom: 12,
  },
  sectionTitle: {
    textAlign: 'right',
    color: '#101820',
    fontSize: 21,
    fontWeight: '700',
  },
  feedSortRow: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-start',
  },
  feedSortPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#f1eee7',
  },
  feedSortPillOn: {
    backgroundColor: '#e8fbfd',
    borderWidth: 1,
    borderColor: 'rgba(8, 184, 200, 0.35)',
  },
  feedSortPillText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#101820',
  },
  feedSortPillTextOn: {
    color: '#087b85',
  },
  feedLoadingText: {
    textAlign: 'center',
    color: '#5c6670',
    fontSize: 15,
    fontWeight: '700',
    paddingVertical: 20,
    paddingHorizontal: 12,
  },
  cards: {
    gap: 14,
  },
  card: {
    overflow: 'hidden',
    borderRadius: 26,
    backgroundColor: '#fff',
    shadowColor: '#101820',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.08,
    shadowRadius: 28,
    elevation: 3,
  },
  imageWrap: {
    position: 'relative',
    height: 190,
  },
  cardSaveBtn: {
    position: 'absolute',
    top: 10,
    left: 10,
    zIndex: 2,
  },
  cardImage: {
    width: '100%',
    height: '100%',
  },
  cardBody: {
    padding: 15,
  },
  cardTop: {
    flexDirection: 'row-reverse',
    gap: 12,
    justifyContent: 'space-between',
  },
  cardTitle: {
    flex: 1,
    textAlign: 'right',
    color: '#101820',
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 22,
  },
  cardPrice: {
    color: '#101820',
    fontSize: 18,
    fontWeight: '800',
  },
  cardMeta: {
    marginTop: 8,
    textAlign: 'right',
    color: '#687076',
    lineHeight: 22,
  },
  featureRow: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 14,
  },
  featurePill: {
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
    color: '#087b85',
    backgroundColor: '#e8fbfd',
    fontSize: 12,
    fontWeight: '600',
  },
  trustStrip: {
    marginTop: 18,
    padding: 15,
    borderRadius: 22,
    backgroundColor: '#fff',
  },
  trustTitle: {
    textAlign: 'right',
    color: '#101820',
    fontWeight: '700',
  },
  trustText: {
    marginTop: 4,
    textAlign: 'right',
    color: '#687076',
  },
  listingDetailsRoot: {
    flex: 1,
    backgroundColor: '#f7f6f2',
  },
  listingDetailsScroll: {
    flex: 1,
  },
  detailContent: {
    padding: 14,
    paddingBottom: 100,
  },
  detailCard: {
    marginTop: 16,
    padding: 18,
    borderRadius: 26,
    backgroundColor: '#fff',
  },
  detailTitle: {
    textAlign: 'right',
    color: '#101820',
    fontSize: 23,
    fontWeight: '700',
    letterSpacing: -0.6,
    lineHeight: 29,
  },
  detailLocation: {
    marginTop: 10,
    textAlign: 'right',
    color: '#687076',
    fontSize: 15,
  },
  statsGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  statBox: {
    minWidth: '47%',
    flex: 1,
    minHeight: 64,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: 'rgba(16,24,32,0.07)',
    borderRadius: 18,
    backgroundColor: '#fbfaf6',
    shadowColor: '#101820',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.035,
    shadowRadius: 12,
    elevation: 1,
    justifyContent: 'space-between',
  },
  statLabelRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  statValue: {
    textAlign: 'right',
    color: '#101820',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  statLabel: {
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 999,
    textAlign: 'right',
    color: '#687076',
    backgroundColor: 'rgba(16,24,32,0.04)',
    fontSize: 11,
    fontWeight: '700',
  },
  detailSectionTitle: {
    marginTop: 22,
    textAlign: 'right',
    color: '#101820',
    fontSize: 19,
    fontWeight: '700',
  },
  detailDescription: {
    marginTop: 8,
    textAlign: 'right',
    color: '#25313b',
    fontSize: 15,
    lineHeight: 26,
  },
  descriptionToggle: {
    alignSelf: 'flex-end',
    marginTop: 8,
    paddingVertical: 2,
  },
  descriptionToggleText: {
    color: '#0799a7',
    fontSize: 13,
    fontWeight: '800',
  },
  reportModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 14,
    backgroundColor: 'rgba(16,24,32,0.28)',
  },
  reportKeyboardAvoidingView: {
    flex: 1,
  },
  reportSheet: {
    maxHeight: '88%',
    padding: 18,
    borderRadius: 28,
    backgroundColor: 'rgba(255,255,255,0.97)',
    shadowColor: '#101820',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.18,
    shadowRadius: 38,
    elevation: 12,
  },
  reportSheetContent: {
    paddingBottom: 2,
  },
  reportSheetHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    gap: 16,
  },
  reportCloseButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    backgroundColor: '#f3f0e9',
  },
  reportCloseText: {
    color: '#101820',
    fontSize: 24,
    lineHeight: 28,
  },
  reportTitle: {
    textAlign: 'right',
    color: '#101820',
    fontSize: 21,
    fontWeight: '800',
  },
  reportSubtitle: {
    marginTop: 6,
    textAlign: 'right',
    color: '#687076',
    fontSize: 14,
  },
  reportReasonList: {
    gap: 8,
    marginTop: 18,
  },
  reportReasonButton: {
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderWidth: 1,
    borderColor: 'rgba(16,24,32,0.07)',
    borderRadius: 18,
    backgroundColor: '#fbfaf6',
  },
  selectedReportReasonButton: {
    borderColor: 'rgba(8,184,200,0.42)',
    backgroundColor: '#e8fbfd',
  },
  reportReasonText: {
    textAlign: 'right',
    color: '#101820',
    fontWeight: '700',
  },
  selectedReportReasonText: {
    color: '#087b85',
  },
  reportOtherField: {
    gap: 7,
    marginTop: 12,
  },
  reportOtherLabel: {
    textAlign: 'right',
    color: '#687076',
    fontSize: 12,
    fontWeight: '700',
  },
  reportOtherInput: {
    minHeight: 76,
    paddingHorizontal: 13,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: 'rgba(16,24,32,0.08)',
    borderRadius: 18,
    color: '#101820',
    backgroundColor: '#fbfaf6',
    fontSize: 14,
    lineHeight: 20,
  },
  reportOtherCounter: {
    alignSelf: 'flex-start',
    color: '#687076',
    fontSize: 12,
    fontWeight: '700',
  },
  reportSubmitButton: {
    alignItems: 'center',
    marginTop: 14,
    padding: 14,
    borderRadius: 999,
    backgroundColor: '#101820',
  },
  disabledReportSubmitButton: {
    opacity: 0.35,
  },
  reportSubmitText: {
    color: '#fff',
    fontWeight: '800',
  },
  reportSuccessBanner: {
    marginTop: 10,
    padding: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(8,184,200,0.14)',
    color: '#065a63',
    textAlign: 'right',
    fontWeight: '800',
  },
  reportErrorBanner: {
    marginTop: 10,
    padding: 10,
    borderRadius: 14,
    backgroundColor: 'rgba(220,53,69,0.1)',
    color: '#a21e2e',
    textAlign: 'right',
    fontWeight: '800',
  },
  publisherCard: {
    marginTop: 16,
    padding: 18,
    borderRadius: 26,
    backgroundColor: '#fff',
  },
  publisherName: {
    textAlign: 'right',
    color: '#101820',
    fontSize: 23,
    fontWeight: '700',
  },
  publisherResponse: {
    marginTop: 4,
    textAlign: 'right',
    color: '#687076',
  },
  chatButton: {
    marginTop: 16,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#101820',
  },
  chatButtonText: {
    textAlign: 'center',
    color: '#fff',
    fontWeight: '700',
  },
  chatButtonDisabled: {
    opacity: 0.55,
  },
  chatHintText: {
    marginTop: 8,
    textAlign: 'right',
    color: '#a21e2e',
    fontWeight: '700',
    fontSize: 13,
  },
  chatScreenRoot: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  chatScreenInner: {
    flex: 1,
  },
  chatHeaderBar: {
    marginHorizontal: 0,
    marginBottom: 0,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e4e5e7',
    backgroundColor: '#ffffff',
  },
  chatHeaderActionText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#101820',
  },
  chatScreenTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#101820',
    letterSpacing: -0.4,
  },
  chatSectionLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#74767e',
    letterSpacing: 1,
  },
  chatSearchBar: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e4e5e7',
    backgroundColor: '#ffffff',
  },
  chatSearchInput: {
    borderWidth: 1,
    borderColor: '#e4e5e7',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    backgroundColor: '#fafafa',
    color: '#101820',
  },
  chatLegalNoticeMobile: {
    paddingHorizontal: 16,
    paddingBottom: 8,
    textAlign: 'right',
    fontSize: 12,
    fontWeight: '500',
    color: '#74767e',
    lineHeight: 17,
  },
  chatListScroll: {
    flex: 1,
  },
  chatListContent: {
    paddingHorizontal: 16,
    paddingBottom: 100,
    flexGrow: 1,
  },
  chatListError: {
    textAlign: 'right',
    fontSize: 13,
    fontWeight: '700',
    color: '#a21e2e',
    marginBottom: 8,
  },
  chatEmptyWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
    minHeight: 200,
  },
  chatEmptyArt: {
    width: 200,
    height: 160,
    overflow: 'hidden',
  },
  chatEmptyArtImage: {
    opacity: 0.98,
  },
  chatMuted: {
    textAlign: 'right',
    color: '#5c6670',
    fontWeight: '700',
    paddingHorizontal: 16,
    marginTop: 8,
  },
  chatCta: {
    marginHorizontal: 16,
    marginTop: 12,
    padding: 14,
    borderRadius: 999,
    backgroundColor: '#101820',
  },
  chatCtaText: {
    textAlign: 'center',
    color: '#fff',
    fontWeight: '900',
  },
  chatThreadRow: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e4e5e7',
    backgroundColor: '#ffffff',
    gap: 6,
  },
  chatThreadRowTop: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  chatThreadTime: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8b949b',
    flexShrink: 0,
  },
  chatThreadPreviewRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  chatThreadPreview: {
    flex: 1,
    textAlign: 'right',
    fontSize: 14,
    fontWeight: '600',
    color: '#5c6670',
  },
  chatThreadUnreadPill: {
    minWidth: 22,
    height: 22,
    paddingHorizontal: 6,
    borderRadius: 999,
    backgroundColor: '#08b8c8',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  chatThreadUnreadPillText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  chatThreadTitle: {
    textAlign: 'right',
    fontSize: 17,
    fontWeight: '800',
    color: '#101820',
  },
  chatThreadMeta: {
    marginTop: 4,
    textAlign: 'right',
    fontSize: 13,
    color: '#687076',
  },
  chatThreadSubtitle: {
    paddingHorizontal: 16,
    marginBottom: 4,
    textAlign: 'right',
    fontSize: 15,
    fontWeight: '800',
    color: '#101820',
  },
  chatThreadBody: {
    flex: 1,
  },
  chatMessagesScroll: {
    flex: 1,
  },
  chatMessagesContent: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    gap: 12,
  },
  chatBubbleColumn: {
    maxWidth: '85%',
    gap: 4,
  },
  chatBubbleColumnMine: {
    alignSelf: 'flex-start',
  },
  chatBubbleColumnOther: {
    alignSelf: 'flex-end',
    alignItems: 'flex-end',
  },
  chatBubble: {
    padding: 12,
    borderRadius: 18,
  },
  chatBubbleMine: {
    backgroundColor: 'rgba(8,184,200,0.2)',
  },
  chatBubbleOther: {
    backgroundColor: '#f5f5f5',
    borderWidth: 1,
    borderColor: '#e4e5e7',
  },
  chatBubbleText: {
    textAlign: 'right',
    fontSize: 15,
    lineHeight: 21,
    color: '#101820',
  },
  chatBubbleTime: {
    fontSize: 11,
    fontWeight: '600',
    color: '#687076',
    paddingHorizontal: 4,
  },
  chatSendError: {
    paddingHorizontal: 16,
    marginBottom: 6,
    textAlign: 'right',
    fontSize: 13,
    fontWeight: '700',
    color: '#a21e2e',
  },
  chatComposerWrap: {
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#e4e5e7',
    backgroundColor: '#ffffff',
  },
  chatComposerBar: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-end',
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(16,24,32,0.1)',
    backgroundColor: '#fafafa',
  },
  chatComposerIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 999,
    backgroundColor: '#101820',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatComposerIconBtnPressed: {
    opacity: 0.88,
  },
  chatInputBar: {
    flex: 1,
    minHeight: 40,
    maxHeight: 120,
    paddingHorizontal: 4,
    paddingVertical: Platform.OS === 'ios' ? 10 : 8,
    fontSize: 16,
    lineHeight: 22,
    color: '#101820',
  },
  chatComposerSendBtn: {
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatComposerSendBtnDisabled: {
    opacity: 0.55,
  },
  chatComposerSendBtnPressed: {
    opacity: 0.75,
  },
  mainShell: {
    flex: 1,
  },
  headerMainSimple: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 48,
    marginHorizontal: 10,
    marginBottom: 4,
    paddingHorizontal: 4,
  },
  headerSideSlotEnd: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 2,
  },
  headerSideSlot: {
    minWidth: 72,
    alignItems: 'center',
    justifyContent: 'center',
  },
  floatingTabBarWrap: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: Platform.OS === 'ios' ? 12 : 10,
    alignItems: 'center',
  },
  floatingTabBar: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: 420,
    paddingVertical: 8,
    paddingHorizontal: 8,
    backgroundColor: '#fff',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(16,24,32,0.07)',
    shadowColor: '#101820',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 28,
    elevation: 14,
  },
  tabBarMessagesSlot: {
    flex: 1,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabBarBadge: {
    position: 'absolute',
    top: 2,
    right: '18%',
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 999,
    backgroundColor: '#d92d20',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  tabBarBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '900',
  },
  tabBarItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44,
    paddingVertical: 4,
    borderRadius: 999,
  },
  tabBarItemActive: {
    backgroundColor: '#e8e6e1',
  },
  tabBarItemPublish: {
    paddingHorizontal: 4,
    backgroundColor: 'rgba(8, 184, 200, 0.08)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(8, 184, 200, 0.22)',
    shadowColor: '#08b8c8',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 18,
    elevation: Platform.OS === 'android' ? 8 : 5,
  },
  tabBarItemActivePublish: {
    backgroundColor: 'rgba(8, 184, 200, 0.2)',
    borderColor: 'rgba(8, 184, 200, 0.35)',
  },
  filterModalRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  filterModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(16, 24, 32, 0.35)',
  },
  filterModalSheet: {
    maxHeight: '78%',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    backgroundColor: '#fbfaf7',
    paddingBottom: Platform.OS === 'ios' ? 28 : 16,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: 'rgba(16,24,32,0.08)',
  },
  filterModalHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    marginTop: 10,
    marginBottom: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(16,24,32,0.12)',
  },
  filterModalHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(16,24,32,0.06)',
  },
  filterModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#101820',
  },
  filterModalClose: {
    fontSize: 15,
    fontWeight: '700',
    color: '#08b8c8',
  },
  filterModalBody: {
    padding: 16,
    paddingBottom: 28,
    gap: 4,
  },
  filterModalHint: {
    marginTop: 16,
    textAlign: 'right',
    fontSize: 13,
    lineHeight: 20,
    color: '#687076',
  },
  filterModalActiveHint: {
    marginTop: 10,
    textAlign: 'right',
    fontSize: 13,
    lineHeight: 20,
    color: '#087b85',
    fontWeight: '600',
  },
  filterModalHintMuted: {
    marginTop: 12,
    textAlign: 'right',
    fontSize: 12,
    lineHeight: 18,
    color: '#9aa3ab',
  },
  phoneButton: {
    marginTop: 10,
    padding: 14,
    borderRadius: 16,
    backgroundColor: '#f1eee7',
  },
  phoneButtonText: {
    textAlign: 'center',
    color: '#101820',
    fontWeight: '700',
  },
  legalFooter: {
    marginTop: 18,
    marginHorizontal: -14,
    marginBottom: -100,
    paddingHorizontal: 18,
    paddingTop: 24,
    paddingBottom: 30,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: '#101820',
    shadowColor: '#101820',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.1,
    shadowRadius: 30,
    elevation: 4,
  },
  footerBrandText: {
    textAlign: 'right',
    color: '#08b8c8',
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: -0.8,
  },
  footerBrandDescription: {
    marginTop: 8,
    textAlign: 'right',
    color: 'rgba(255,255,255,0.7)',
    fontSize: 13,
    lineHeight: 22,
  },
  footerSection: {
    marginTop: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.045)',
  },
  legalFooterTitle: {
    textAlign: 'right',
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
  legalFooterText: {
    marginTop: 6,
    textAlign: 'right',
    color: 'rgba(255,255,255,0.68)',
    fontSize: 13,
    lineHeight: 22,
  },
  footerReportNotice: {
    marginTop: 10,
    marginBottom: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.045)',
  },
  footerLinks: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  footerLinkPill: {
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    color: 'rgba(255,255,255,0.82)',
    backgroundColor: 'rgba(255,255,255,0.08)',
    fontSize: 12,
    fontWeight: '700',
  },
  footerFinePrint: {
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.1)',
    textAlign: 'right',
    color: 'rgba(255,255,255,0.58)',
    fontSize: 12,
    lineHeight: 21,
  },
});